name: Build Lingmo DE Docker Image

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Ubuntu 24.04 Lingmo Docker Image
      run: docker buildx build 
           --progress=plain 
           --file Images/Ubuntu-LingmoDE 
           --tag pikachuim/ubuntu:24.04-lingmo 
           --build-arg OS_VERSION=24.04 
           --build-arg OS_VERSHOW=24.04 
           --build-arg OS_SYSTEMS=ubuntu 
           .
    
    - uses: actions/checkout@v4
    - name: Build the Debian 12.XX Lingmo Docker Image
      run: docker buildx build 
           --progress=plain 
           --file Images/Debian-LingmoDE 
           --tag pikachuim/debian:12.00-lingmo 
           --build-arg OS_VERSION=12.00 
           --build-arg OS_VERSHOW=12.00 
           --build-arg OS_SYSTEMS=debian 
           .
